CREATE TABLE USERS (SALT CHARACTER(16) PRIMARY KEY,
                    ALIAS VARCHAR(16) NOT NULL,
                    PASSPHRASE CHARACTER(64));

CREATE TABLE CHATROOMS (SALT CHARACTER(16) PRIMARY KEY,
                        NAME VARCHAR(16) NOT NULL);